# Generated by Django 4.2.1 on 2023-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_business_id_alter_freelancer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
